name: Build Kernel Modules

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Model'
        required: true
        default: 'ithc'
        type: choice
        options:
          - ithc
          # Add more models here if needed
      os-version:
        description: 'OS Version'
        required: true
        type: string
      device-type:
        description: 'Device Type'
        required: true
        default: 'generic-amd64'
        type: choice
        options:
          - generic-amd64
          # Add more device types here if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensures submodules are also checked out

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget build-essential libelf-dev bc dkms

    - name: Make build script executable
      run: chmod +x ./scripts/build.sh

    - name: Download artifacts
      id: download-artifacts
      uses: actions/download-artifact@v4  # Updated to v4
      with:
        name: kernel-module-${{ github.event.inputs.model }}-${{ github.event.inputs.os-version }}-${{ github.event.inputs.device-type }}
        path: out/src_${{ github.event.inputs.model }}_${{ github.event.inputs.os-version }}-${{ github.event.inputs.device-type }}
      continue-on-error: true  # Continue if the artifact does not exist

    - name: Check if artifact exists
      id: check-artifact
      run: |
        if [ -d "out/src_${{ github.event.inputs.model }}_${{ github.event.inputs.os-version }}-${{ github.event.inputs.device-type }}" ]; then
          echo "Artifact already exists. Skipping build."
          echo "SKIP_BUILD=true" >> $GITHUB_ENV
        else
          echo "Artifact does not exist. Proceeding with build."
          echo "SKIP_BUILD=false" >> $GITHUB_ENV
        fi

    - name: Build kernel module
      if: env.SKIP_BUILD == 'false'
      run: |
        ./scripts/build.sh -i src/${{ github.event.inputs.model }} -o out -v ${{ github.event.inputs.os-version }} -s ${{ github.event.inputs.device-type }}
      env:
        OS_VERSION: ${{ github.event.inputs.os-version }}

    - name: Upload artifacts
      if: env.SKIP_BUILD == 'false'
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: kernel-module-${{ github.event.inputs.model }}-${{ github.event.inputs.os-version }}-${{ github.event.inputs.device-type }}
        path: out/src/${{ github.event.inputs.model }}_${{ github.event.inputs.device-type }}-${{ github.event.inputs.os-version }}